version 0.2

phases:
  pre-build:
    - echo Logging into Amazon ECR
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    - echo Build started on `date`
    - docker build . 